name: bird_triage_ai
description: "A mobile app that helps users determine whether a bird needs to be rescued using AI-powered photo analysis."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  camera: ^0.10.5+5

  # Location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # HTTP requests for AI API
  http: ^1.1.0
  dio: ^5.3.2

  # UI components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # State management
  provider: ^6.1.1

  # Utilities
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 